config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/songs")
  scope "/admin" do
    get "/", to: "admin#index", as: :admin
    get :login, to: "admin#login", as: :admin_login
    get :callback, to: "admin#callback", as: :admin_callback
    post :start_party, to: "admin#start_party", as: :start_party
    get :end_party, to: "admin#end_party", as: :end_party
  end
  scope "/songs" do
    get "/", to: "songs#index", as: :songs
    get :search, to: "songs#search", as: :songs_search
    post :enqueue, to: "songs#enqueue", as: :songs_enqueue
    get :inactive, to: "songs#inactive", as: :songs_inactive
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_token

  def index
    redirect_to admin_login_path and return if !Spotify.authorized?

    @playlists = Spotify::Playlist.all
  end

  def login
    redirect_to Spotify.auth_url
  end

  def callback
    res = Spotify.authorize(params[:code])

    if res.code != 200
      head res.body
    else
      redirect_to admin_path
    end
  end

  def start_party
    playlist_id = params[:playlist_uri].scan(/[^:]*$/)[0]
    tracks = Spotify::Playlist.get_tracks(playlist_id)
    tracks = tracks.shuffle.map { |t| t["uri"] }
    playlist = Spotify::Playlist.create(name: "Jukebox #{DateTime.current.strftime("%Y%m%d%H%M")}", public: false)
    Spotify::Playlist.add(playlist["id"], tracks, 0, false)
    Rails.cache.delete("spotify_queue_index")
    Rails.cache.write("spotify_playlist_id", playlist["id"])
    Spotify::Player.toggle_shuffle(false)
    Spotify::Player.play(playlist["uri"])

    flash[:success] = "Party Started!!"
    redirect_to admin_path
  end

  def end_party
    Rails.cache.delete("spotify_queue_index")
    Rails.cache.delete("spotify_playlist_id")
    Rails.cache.delete("spotify_access_token")
    Rails.cache.delete("spotify_refresh_token")

    flash[:success] = "Party Ended :("
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def require_token
    if params[:_token] != ENV["access_token"] && session[:_token] != ENV["access_token"]
      render file: File.join(Rails.root, 'public/404'), formats: [:html], status: 404, layout: false
    end
    session[:_token] ||= params[:_token] if params[:_token]
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :check_active, only: [:index]
  before_action :set_currents, except: [:search, :inactive]

  def index
  end

  def inactive
    render :inactive, layout: "blank"
  end

  def search
    @query = params[:query]
    @results = Spotify::Track.search(@query)
    @tracks = @results["tracks"]["items"]
  end

  def enqueue
    track_index = @tracks.map {|t| t["id"]}.index(params[:track_id])
    if track_index && (track_index < @current_index || track_index > @queue_index)
      r = Spotify::Playlist.reorder(@playlist_id, track_index, @queue_index)
    elsif !track_index
      r = Spotify::Playlist.add(@playlist_id, params[:track_uri], @queue_index)
    end

    flash[:success] = "#{params[:track_name]} added to queue!"
    redirect_to songs_search_path(query: params[:query])
  end

  private

  def check_active
    redirect_to :songs_inactive and return unless Spotify.authorized?
  end

  def set_currents
    @player = Spotify::Player.get
    @current_track = @player["item"]
    @playlist_id = Rails.cache.fetch("spotify_playlist_id") do
      @player["context"]["uri"].scan(/[^:]*$/)[0]
    end
    @tracks = Spotify::Playlist.get_tracks(@playlist_id)
    @current_index = @tracks.index { |track| @current_track["id"] == track["id"] } || -1
    @queue_index = Rails.cache.read("spotify_queue_index")
    puts "QUEUE INDEX INITIAL: #{ @queue_index }"
    if @queue_index.nil? || @queue_index <= @current_index + 1
      @queue_index = [@tracks.length, @current_index + 2].min
    end
    @queue_index += 1 if @queue_index == @current_index + 1 &&
      @current_track["duration_ms"] - @player["progress_ms"] < 5000
    Rails.cache.write("spotify_queue_index", @queue_index)
    puts "QUEUE INDEX FINAL: #{ @queue_index }"
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/admin/index.html.erb
<iv class="uk-container admin">
  <h1 class="uk-heading-divider">
    <i class="fa fa-music uk-margin-small-right"></i> Party Jukebox
    <i class="fa fa-music uk-margin-small-left"></i>
  </h1><!-- .uk-heading-divider -->
  <div class="uk-grid-match uk-text-center" uk-grid>
    <% @playlists.each do |playlist| %>
      <div class="uk-width-1-1 uk-width-1-3@m">
        <div class="uk-card uk-card-default">
          <div class="uk-card-header">
            <h3 class="uk-card-title"><%= playlist[:name] %></h3><!-- .uk-card-body -->
          </div>
          <div class="uk-card-body">
            <% img = playlist[:images].select { |i| i["width"] == i["height"] }.first %>
            <%= image_tag img && img["url"] || "http://via.placeholder.com/300x300", height: "150px", width: "150px" %>
          </div><!-- .uk-card-body -->
          <div class="uk-card-footer">
            <%= form_tag start_party_path do %>
              <%= hidden_field_tag "playlist_uri", playlist[:uri] %>
              <%= button_tag class: "uk-button uk-button-primary uk-width-1-1" do %>
                <span class="start-party-icon">
                  <i class="fa fa-play"></i>
                </span><!-- .start-party-icon -->
                Start Party
              <% end %>
            <% end %>
          </div><!-- .uk-card-footer -->
        </div><!-- .uk-card -->
      </div>
    <% end %>
  </div><!-- .uk-grid-match uk-child-width-expands@s -->
</div><!-- .uk-container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Party Jukebox</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; bottom: #transparent-sticky-navbar">
      <nav class="uk-navbar-container" uk-navbar style="position: relative; z-index: 980;">
        <div class="uk-navbar-left uk-width-1-1">
          <%= link_to songs_path, class: "uk-navbar-item uk-logo uk-width-1-6" do %>
            <i class="fa fa-home"></i>
          <% end %>
          <div class="uk-navbar-item uk-width-5-6">
            <%= form_tag songs_search_path, method: :get, class: "uk-search uk-search-default uk-width-1-1" do %>
              <button type="submit" href="" class="uk-search-icon-flip" uk-search-icon></button>
              <input class="uk-search-input songs-search" type="search" name="query" placeholder="Search...">
            <% end %>
          </div><!-- .uk-navbar-item -->
        </div>
      </nav>
    </div>
    <div class="uk-container">
      <% if flash[:success] %>
        <div class="uk-alert-success uk-margin-top uk-margin-bottom" uk-alert>
          <a class="uk-alert-close" uk-close></a>
          <p><%= flash[:success] %></p>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Party Jukebox</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/inactive.html.erb
<div class="uk-container">
  <div class="uk-align-center">
    <h1 class="uk-heading-divider">Party Jukebox is Inactive.</h1>
    <img src="/kev.jpg" alt="">
  </div><!-- .uk-align-center -->
</div>

app/views/songs/index.html.erb
<div class="uk-container songs">
  <div class="uk-grid-match uk-text-center" uk-grid>
    <% @tracks[@current_index..(@current_index + 5)].each_with_index do |track, index| %>
      <div class="uk-width-1-3@m">
        <div class="uk-card <%= index == 0 ? "uk-card-primary" : "uk-card-default" %>">
          <div class="uk-card-header">
            <h4 class="uk-card-title"><%= track["name"] %></h4><!-- .uk-card-body -->
          </div>
          <div class="uk-card-body">
            <% img = track["album"]["images"].select { |i| i["width"] == i["height"] }.first %>
            <%= image_tag img && img["url"] || "http://via.placeholder.com/300x300", height: "150px", width: "150px" %>
          </div><!-- .uk-card-body -->
          <div class="uk-card-footer">
            <h5><%= track["artists"][0]["name"] %></h5>
          </div><!-- .uk-card-footer -->
        </div><!-- .uk-card -->
      </div>
    <% end %>
  </div><!-- .uk-grid-match uk-child-width-expands@s -->
</div><!-- .uk-container -->

app/views/songs/search.html.erb
<div class="uk-container songs">
  <div class="uk-text-center" uk-grid>
    <% @tracks.each do |track| %>
      <div class="uk-width-1-1 uk-width-1-3@m">
        <div class="uk-card uk-card-default">
          <div class="uk-card-header">
            <h4 class="uk-card-title"><%= track["name"] %></h4><!-- .uk-card-body -->
          </div>
          <div class="uk-card-body">
            <% img = track["album"]["images"].select { |i| i["width"] == i["height"] }.first %>
            <%= image_tag img && img["url"] || "http://via.placeholder.com/300x300", height: "150px", width: "150px" %>
          </div><!-- .uk-card-body -->
          <div class="uk-card-footer">
            <h5><%= track["artists"][0]["name"] %></h5>
            <hr>
            <%= form_tag songs_enqueue_path, class: "enqueue-form" do %>
              <%= hidden_field_tag "track_id", track["id"] %>
              <%= hidden_field_tag "track_name", track["name"] %>
              <%= hidden_field_tag "track_uri", track["uri"] %>
              <%= hidden_field_tag "query", @query %>
              <%= button_tag class: "uk-button uk-button-primary", data: { "uk-confirm" => "Add to queue?" } do %>
                <i class="fa fa-plus uk-margin-small-right"></i> Add to Queue
              <% end %>
            <% end %>
          </div><!-- .uk-card-footer -->
        </div><!-- .uk-card -->
      </div>
    <% end %>
  </div><!-- .uk-grid-match uk-child-width-expands@s -->
</div><!-- .uk-container -->